#!/usr/bin/env bash
/*This program prints Best School 10 times. */


#include <stdio.h>
#include <stdlib.h>

int main () {
 int i;   
	for (int i =0; i < 11; i++);
         {
		printf("Best School")
         }
		return 0;
}
