#!/usr/bin/env bash
#This program prints Best School 10 times. 


#include <stdio.h>
#include <stdlib.h>

int main () 
{
 int x;   
	for (x=0; x < 10; x=x+1)
         {
		printf("Best School, x");
         }
 return(0);
}
