#!/usr/bin/env bash
# Bash script with a while loop that displays Best School 10 times but for the 9th iteration displays Best School.

i=1
while ["$i" <=10]
do
	if ["$i"=4];then
		echo "bad luck"
	elif["$i"=8]
		echo "good luck"
		echo "Best School"
	fi
	(i++)
done


