#!/usr/bin/env bash
# While loop that displays numbers 1 to 20. Displays 4 then bad luck from China. Displays 9 then bad luck from Japan. Displays 17 then bad luck from Italy. 

i=1
while [ $i<=20 ] 
do echo "$i"
	case $i in
		4) echo "bad luck from China"
			9) echo "bad luck from Japan"
			17) echo "bad luck for Italy"
	esac
	((i++))
done

